server:
  port: 8090

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/exchanges
    hikari:
      data-source-properties:
        useLocalSessionState: true
        createDatabaseIfNotExist: true
        useSSL: false
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: "update"
      dialect: org.hibernate.dialect.MySQLDialect
      show_sql: true
